baseURL = '/'
languageCode = 'en-us'
title = 'Stargaze'
theme = 'PaperMod'

[markup]
  [markup.goldmark]
    renderer = { unsafe = true }

[params]
  description = 'Orbital data centers'
  author = 'Stargaze Team'
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButton = false
  ShowAllPagesInMenu = false
  defaultTheme = "dark"
  DisableThemeToggle = true
  comments = false
  assets = {disableHLJS = false, favicon = '/favicon.ico', favicon_dark = '/favicon.ico', favicon_16x16 = '/favicon-16x16.png', favicon_32x32 = '/favicon-32x32.png'}

  [params.homepage]
    cover = {hidden = false, caption = '', type = 'image', src = '/assets/stargaze.jpg'}
    showMore = false
    contentType = 'posts'
    ShowAllPagesInHomepage = false
    NumberOfFeaturedPosts = 0
    socialIcon = ''

[menu]
  [[menu.main]]
    identifier = "motivation"
    name = "Motivation"
    url = "/motivation/"
    weight = 10
  [[menu.main]]
    identifier = "companies"
    name = "Companies"
    url = "/companies/"
    weight = 20
  [[menu.main]]
    identifier = "technical"
    name = "Technical"
    url = "/technical/"
    weight = 30
  [[menu.main]]
    identifier = "economics"
    name = "Economics"
    url = "/economics/"
    weight = 40
  [[menu.main]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = 70